/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_13.h"
#include "Pin_13_aliases.h"
#include "PWM_1.h"
#include "Clock_1.h"
#include "SmartIO_1.h"
#include "PWM_2.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "CapSense_1.h"
#include "CapSense_1_Control.h"
#include "CapSense_1_Filter.h"
#include "CapSense_1_Processing.h"
#include "CapSense_1_Sensing.h"
#include "CapSense_1_Structure.h"
#include "CapSense_1_Tuner.h"
#include "CapSense_1_Configuration.h"
#include "CapSense_1_SensingCSD_LL.h"
#include "CapSense_1_RegisterMap.h"
#include "CapSense_1_Centroid_LL.h"
#include "CapSense_1_SmartSense_LL.h"
#include "EZI2C_1.h"
#include "EZI2C_1_PINS.h"
#include "EZI2C_1_PVT.h"
#include "EZI2C_1_EZI2C.h"
#include "EZI2C_1_EZI2C_PVT.h"
#include "EZI2C_1_BOOT.h"
#include "Pin_10.h"
#include "Pin_10_aliases.h"
#include "Pin_9.h"
#include "Pin_9_aliases.h"
#include "Pin_8.h"
#include "Pin_8_aliases.h"
#include "Pin_7.h"
#include "Pin_7_aliases.h"
#include "Pin_6.h"
#include "Pin_6_aliases.h"
#include "Pin_5.h"
#include "Pin_5_aliases.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "Clock_2.h"
#include "CapSense_1_ISR.h"
#include "EZI2C_1_SCBCLK.h"
#include "EZI2C_1_sda.h"
#include "EZI2C_1_sda_aliases.h"
#include "EZI2C_1_scl.h"
#include "EZI2C_1_scl_aliases.h"
#include "EZI2C_1_SCB_IRQ.h"
#include "UART_1_tx.h"
#include "UART_1_tx_aliases.h"
#include "UART_1_rx.h"
#include "UART_1_rx_aliases.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

